# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculadora2.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculadora2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63\x61lculadora2.proto\x12\x0b\x63\x61lculadora\"/\n\x0bMensajeSuma\x12\x0f\n\x07numero1\x18\x01 \x01(\x01\x12\x0f\n\x07numero2\x18\x02 \x01(\x01\"\'\n\x12RespuestaOperacion\x12\x11\n\tresultado\x18\x01 \x01(\x01\x32S\n\x0b\x43\x61lculadora\x12\x44\n\x05Sumar\x12\x18.calculadora.MensajeSuma\x1a\x1f.calculadora.RespuestaOperacion\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MENSAJESUMA']._serialized_start=35
  _globals['_MENSAJESUMA']._serialized_end=82
  _globals['_RESPUESTAOPERACION']._serialized_start=84
  _globals['_RESPUESTAOPERACION']._serialized_end=123
  _globals['_CALCULADORA']._serialized_start=125
  _globals['_CALCULADORA']._serialized_end=208
# @@protoc_insertion_point(module_scope)
