# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from. import calculadora_pb2 as calculadora__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in calculadora_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SumaServiceStub(object):
    """─────────────────────────────────────────────
    Definición de los servicios atómicos
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sumar = channel.unary_unary(
                '/calculadora.SumaService/Sumar',
                request_serializer=calculadora__pb2.Numeros.SerializeToString,
                response_deserializer=calculadora__pb2.Respuesta.FromString,
                _registered_method=True)


class SumaServiceServicer(object):
    """─────────────────────────────────────────────
    Definición de los servicios atómicos
    ─────────────────────────────────────────────

    """

    def Sumar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SumaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sumar': grpc.unary_unary_rpc_method_handler(
                    servicer.Sumar,
                    request_deserializer=calculadora__pb2.Numeros.FromString,
                    response_serializer=calculadora__pb2.Respuesta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculadora.SumaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculadora.SumaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SumaService(object):
    """─────────────────────────────────────────────
    Definición de los servicios atómicos
    ─────────────────────────────────────────────

    """

    @staticmethod
    def Sumar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.SumaService/Sumar',
            calculadora__pb2.Numeros.SerializeToString,
            calculadora__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RestaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Restar = channel.unary_unary(
                '/calculadora.RestaService/Restar',
                request_serializer=calculadora__pb2.Numeros.SerializeToString,
                response_deserializer=calculadora__pb2.Respuesta.FromString,
                _registered_method=True)


class RestaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Restar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Restar': grpc.unary_unary_rpc_method_handler(
                    servicer.Restar,
                    request_deserializer=calculadora__pb2.Numeros.FromString,
                    response_serializer=calculadora__pb2.Respuesta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculadora.RestaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculadora.RestaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RestaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Restar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.RestaService/Restar',
            calculadora__pb2.Numeros.SerializeToString,
            calculadora__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MultiplicacionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Multiplicar = channel.unary_unary(
                '/calculadora.MultiplicacionService/Multiplicar',
                request_serializer=calculadora__pb2.Numeros.SerializeToString,
                response_deserializer=calculadora__pb2.Respuesta.FromString,
                _registered_method=True)


class MultiplicacionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Multiplicar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultiplicacionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Multiplicar': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiplicar,
                    request_deserializer=calculadora__pb2.Numeros.FromString,
                    response_serializer=calculadora__pb2.Respuesta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculadora.MultiplicacionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculadora.MultiplicacionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MultiplicacionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Multiplicar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.MultiplicacionService/Multiplicar',
            calculadora__pb2.Numeros.SerializeToString,
            calculadora__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DivisionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Dividir = channel.unary_unary(
                '/calculadora.DivisionService/Dividir',
                request_serializer=calculadora__pb2.Numeros.SerializeToString,
                response_deserializer=calculadora__pb2.Respuesta.FromString,
                _registered_method=True)


class DivisionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Dividir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DivisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Dividir': grpc.unary_unary_rpc_method_handler(
                    servicer.Dividir,
                    request_deserializer=calculadora__pb2.Numeros.FromString,
                    response_serializer=calculadora__pb2.Respuesta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculadora.DivisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculadora.DivisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DivisionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Dividir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.DivisionService/Dividir',
            calculadora__pb2.Numeros.SerializeToString,
            calculadora__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OrquestadorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Calcular = channel.unary_unary(
                '/calculadora.OrquestadorService/Calcular',
                request_serializer=calculadora__pb2.Expresion.SerializeToString,
                response_deserializer=calculadora__pb2.Respuesta.FromString,
                _registered_method=True)


class OrquestadorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Calcular(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrquestadorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Calcular': grpc.unary_unary_rpc_method_handler(
                    servicer.Calcular,
                    request_deserializer=calculadora__pb2.Expresion.FromString,
                    response_serializer=calculadora__pb2.Respuesta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculadora.OrquestadorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculadora.OrquestadorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrquestadorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Calcular(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.OrquestadorService/Calcular',
            calculadora__pb2.Expresion.SerializeToString,
            calculadora__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
