# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculadora.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculadora.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\x12\x0b\x63\x61lculadora\"%\n\x07Numeros\x12\x0c\n\x04num1\x18\x01 \x01(\x01\x12\x0c\n\x04num2\x18\x02 \x01(\x01\"E\n\tRespuesta\x12\x0e\n\x04\x64\x61ta\x18\x01 \x01(\x01H\x00\x12\x0f\n\x05\x65rror\x18\x02 \x01(\tH\x00\x12\n\n\x02id\x18\x03 \x01(\tB\x0b\n\tresultado\"%\n\tExpresion\x12\x0c\n\x04\x65xpr\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t2D\n\x0bSumaService\x12\x35\n\x05Sumar\x12\x14.calculadora.Numeros\x1a\x16.calculadora.Respuesta2F\n\x0cRestaService\x12\x36\n\x06Restar\x12\x14.calculadora.Numeros\x1a\x16.calculadora.Respuesta2T\n\x15MultiplicacionService\x12;\n\x0bMultiplicar\x12\x14.calculadora.Numeros\x1a\x16.calculadora.Respuesta2J\n\x0f\x44ivisionService\x12\x37\n\x07\x44ividir\x12\x14.calculadora.Numeros\x1a\x16.calculadora.Respuesta2P\n\x12OrquestadorService\x12:\n\x08\x43\x61lcular\x12\x16.calculadora.Expresion\x1a\x16.calculadora.Respuestab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMEROS']._serialized_start=34
  _globals['_NUMEROS']._serialized_end=71
  _globals['_RESPUESTA']._serialized_start=73
  _globals['_RESPUESTA']._serialized_end=142
  _globals['_EXPRESION']._serialized_start=144
  _globals['_EXPRESION']._serialized_end=181
  _globals['_SUMASERVICE']._serialized_start=183
  _globals['_SUMASERVICE']._serialized_end=251
  _globals['_RESTASERVICE']._serialized_start=253
  _globals['_RESTASERVICE']._serialized_end=323
  _globals['_MULTIPLICACIONSERVICE']._serialized_start=325
  _globals['_MULTIPLICACIONSERVICE']._serialized_end=409
  _globals['_DIVISIONSERVICE']._serialized_start=411
  _globals['_DIVISIONSERVICE']._serialized_end=485
  _globals['_ORQUESTADORSERVICE']._serialized_start=487
  _globals['_ORQUESTADORSERVICE']._serialized_end=567
# @@protoc_insertion_point(module_scope)
