# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from. import calculadora2_pb2 as calculadora2__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in calculadora2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculadoraStub(object):
    """El servicio de la calculadora.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sumar = channel.unary_unary(
                '/calculadora.Calculadora/Sumar',
                request_serializer=calculadora2__pb2.MensajeSuma.SerializeToString,
                response_deserializer=calculadora2__pb2.RespuestaOperacion.FromString,
                _registered_method=True)


class CalculadoraServicer(object):
    """El servicio de la calculadora.
    """

    def Sumar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculadoraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sumar': grpc.unary_unary_rpc_method_handler(
                    servicer.Sumar,
                    request_deserializer=calculadora2__pb2.MensajeSuma.FromString,
                    response_serializer=calculadora2__pb2.RespuestaOperacion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculadora.Calculadora', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculadora.Calculadora', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Calculadora(object):
    """El servicio de la calculadora.
    """

    @staticmethod
    def Sumar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.Calculadora/Sumar',
            calculadora2__pb2.MensajeSuma.SerializeToString,
            calculadora2__pb2.RespuestaOperacion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
