# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dbaas_pb2 as dbaas__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dbaas_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """─────────────────────────────────────────────
    MS3 — AUTH SERVICE
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/dbaas.AuthService/Register',
                request_serializer=dbaas__pb2.RegisterRequest.SerializeToString,
                response_deserializer=dbaas__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/dbaas.AuthService/Login',
                request_serializer=dbaas__pb2.LoginRequest.SerializeToString,
                response_deserializer=dbaas__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.ValidateToken = channel.unary_unary(
                '/dbaas.AuthService/ValidateToken',
                request_serializer=dbaas__pb2.TokenRequest.SerializeToString,
                response_deserializer=dbaas__pb2.TokenPayload.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """─────────────────────────────────────────────
    MS3 — AUTH SERVICE
    ─────────────────────────────────────────────

    """

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=dbaas__pb2.RegisterRequest.FromString,
                    response_serializer=dbaas__pb2.AuthResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=dbaas__pb2.LoginRequest.FromString,
                    response_serializer=dbaas__pb2.AuthResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=dbaas__pb2.TokenRequest.FromString,
                    response_serializer=dbaas__pb2.TokenPayload.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbaas.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dbaas.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """─────────────────────────────────────────────
    MS3 — AUTH SERVICE
    ─────────────────────────────────────────────

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.AuthService/Register',
            dbaas__pb2.RegisterRequest.SerializeToString,
            dbaas__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.AuthService/Login',
            dbaas__pb2.LoginRequest.SerializeToString,
            dbaas__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.AuthService/ValidateToken',
            dbaas__pb2.TokenRequest.SerializeToString,
            dbaas__pb2.TokenPayload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AdminServiceStub(object):
    """─────────────────────────────────────────────
    MS4 — ADMIN SERVICE
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDatabase = channel.unary_unary(
                '/dbaas.AdminService/CreateDatabase',
                request_serializer=dbaas__pb2.DatabaseRequest.SerializeToString,
                response_deserializer=dbaas__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DropDatabase = channel.unary_unary(
                '/dbaas.AdminService/DropDatabase',
                request_serializer=dbaas__pb2.DatabaseRequest.SerializeToString,
                response_deserializer=dbaas__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListDatabases = channel.unary_unary(
                '/dbaas.AdminService/ListDatabases',
                request_serializer=dbaas__pb2.ListDbRequest.SerializeToString,
                response_deserializer=dbaas__pb2.ListDbResponse.FromString,
                _registered_method=True)
        self.CreateTable = channel.unary_unary(
                '/dbaas.AdminService/CreateTable',
                request_serializer=dbaas__pb2.CreateTableRequest.SerializeToString,
                response_deserializer=dbaas__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DropTable = channel.unary_unary(
                '/dbaas.AdminService/DropTable',
                request_serializer=dbaas__pb2.TableRequest.SerializeToString,
                response_deserializer=dbaas__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListTables = channel.unary_unary(
                '/dbaas.AdminService/ListTables',
                request_serializer=dbaas__pb2.TableRequest.SerializeToString,
                response_deserializer=dbaas__pb2.ListTablesResponse.FromString,
                _registered_method=True)


class AdminServiceServicer(object):
    """─────────────────────────────────────────────
    MS4 — ADMIN SERVICE
    ─────────────────────────────────────────────

    """

    def CreateDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatabases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDatabase,
                    request_deserializer=dbaas__pb2.DatabaseRequest.FromString,
                    response_serializer=dbaas__pb2.StatusResponse.SerializeToString,
            ),
            'DropDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.DropDatabase,
                    request_deserializer=dbaas__pb2.DatabaseRequest.FromString,
                    response_serializer=dbaas__pb2.StatusResponse.SerializeToString,
            ),
            'ListDatabases': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatabases,
                    request_deserializer=dbaas__pb2.ListDbRequest.FromString,
                    response_serializer=dbaas__pb2.ListDbResponse.SerializeToString,
            ),
            'CreateTable': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTable,
                    request_deserializer=dbaas__pb2.CreateTableRequest.FromString,
                    response_serializer=dbaas__pb2.StatusResponse.SerializeToString,
            ),
            'DropTable': grpc.unary_unary_rpc_method_handler(
                    servicer.DropTable,
                    request_deserializer=dbaas__pb2.TableRequest.FromString,
                    response_serializer=dbaas__pb2.StatusResponse.SerializeToString,
            ),
            'ListTables': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTables,
                    request_deserializer=dbaas__pb2.TableRequest.FromString,
                    response_serializer=dbaas__pb2.ListTablesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbaas.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dbaas.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService(object):
    """─────────────────────────────────────────────
    MS4 — ADMIN SERVICE
    ─────────────────────────────────────────────

    """

    @staticmethod
    def CreateDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.AdminService/CreateDatabase',
            dbaas__pb2.DatabaseRequest.SerializeToString,
            dbaas__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.AdminService/DropDatabase',
            dbaas__pb2.DatabaseRequest.SerializeToString,
            dbaas__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatabases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.AdminService/ListDatabases',
            dbaas__pb2.ListDbRequest.SerializeToString,
            dbaas__pb2.ListDbResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.AdminService/CreateTable',
            dbaas__pb2.CreateTableRequest.SerializeToString,
            dbaas__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.AdminService/DropTable',
            dbaas__pb2.TableRequest.SerializeToString,
            dbaas__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.AdminService/ListTables',
            dbaas__pb2.TableRequest.SerializeToString,
            dbaas__pb2.ListTablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CrudServiceStub(object):
    """─────────────────────────────────────────────
    MS5 — CRUD SERVICE
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_unary(
                '/dbaas.CrudService/Insert',
                request_serializer=dbaas__pb2.IROperation.SerializeToString,
                response_deserializer=dbaas__pb2.CrudResponse.FromString,
                _registered_method=True)
        self.Find = channel.unary_unary(
                '/dbaas.CrudService/Find',
                request_serializer=dbaas__pb2.IROperation.SerializeToString,
                response_deserializer=dbaas__pb2.FindResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/dbaas.CrudService/Update',
                request_serializer=dbaas__pb2.IROperation.SerializeToString,
                response_deserializer=dbaas__pb2.CrudResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/dbaas.CrudService/Delete',
                request_serializer=dbaas__pb2.IROperation.SerializeToString,
                response_deserializer=dbaas__pb2.CrudResponse.FromString,
                _registered_method=True)


class CrudServiceServicer(object):
    """─────────────────────────────────────────────
    MS5 — CRUD SERVICE
    ─────────────────────────────────────────────

    """

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Find(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrudServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=dbaas__pb2.IROperation.FromString,
                    response_serializer=dbaas__pb2.CrudResponse.SerializeToString,
            ),
            'Find': grpc.unary_unary_rpc_method_handler(
                    servicer.Find,
                    request_deserializer=dbaas__pb2.IROperation.FromString,
                    response_serializer=dbaas__pb2.FindResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=dbaas__pb2.IROperation.FromString,
                    response_serializer=dbaas__pb2.CrudResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=dbaas__pb2.IROperation.FromString,
                    response_serializer=dbaas__pb2.CrudResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbaas.CrudService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dbaas.CrudService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CrudService(object):
    """─────────────────────────────────────────────
    MS5 — CRUD SERVICE
    ─────────────────────────────────────────────

    """

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.CrudService/Insert',
            dbaas__pb2.IROperation.SerializeToString,
            dbaas__pb2.CrudResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Find(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.CrudService/Find',
            dbaas__pb2.IROperation.SerializeToString,
            dbaas__pb2.FindResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.CrudService/Update',
            dbaas__pb2.IROperation.SerializeToString,
            dbaas__pb2.CrudResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.CrudService/Delete',
            dbaas__pb2.IROperation.SerializeToString,
            dbaas__pb2.CrudResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class QueryServiceStub(object):
    """─────────────────────────────────────────────
    MS6 — QUERY / AGGREGATION SERVICE
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Count = channel.unary_unary(
                '/dbaas.QueryService/Count',
                request_serializer=dbaas__pb2.IROperation.SerializeToString,
                response_deserializer=dbaas__pb2.ScalarResponse.FromString,
                _registered_method=True)
        self.Sum = channel.unary_unary(
                '/dbaas.QueryService/Sum',
                request_serializer=dbaas__pb2.IROperation.SerializeToString,
                response_deserializer=dbaas__pb2.ScalarResponse.FromString,
                _registered_method=True)
        self.Avg = channel.unary_unary(
                '/dbaas.QueryService/Avg',
                request_serializer=dbaas__pb2.IROperation.SerializeToString,
                response_deserializer=dbaas__pb2.ScalarResponse.FromString,
                _registered_method=True)
        self.Distinct = channel.unary_unary(
                '/dbaas.QueryService/Distinct',
                request_serializer=dbaas__pb2.IROperation.SerializeToString,
                response_deserializer=dbaas__pb2.DistinctResponse.FromString,
                _registered_method=True)
        self.Join = channel.unary_unary(
                '/dbaas.QueryService/Join',
                request_serializer=dbaas__pb2.IROperation.SerializeToString,
                response_deserializer=dbaas__pb2.JoinResponse.FromString,
                _registered_method=True)


class QueryServiceServicer(object):
    """─────────────────────────────────────────────
    MS6 — QUERY / AGGREGATION SERVICE
    ─────────────────────────────────────────────

    """

    def Count(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Avg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Distinct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Join(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Count': grpc.unary_unary_rpc_method_handler(
                    servicer.Count,
                    request_deserializer=dbaas__pb2.IROperation.FromString,
                    response_serializer=dbaas__pb2.ScalarResponse.SerializeToString,
            ),
            'Sum': grpc.unary_unary_rpc_method_handler(
                    servicer.Sum,
                    request_deserializer=dbaas__pb2.IROperation.FromString,
                    response_serializer=dbaas__pb2.ScalarResponse.SerializeToString,
            ),
            'Avg': grpc.unary_unary_rpc_method_handler(
                    servicer.Avg,
                    request_deserializer=dbaas__pb2.IROperation.FromString,
                    response_serializer=dbaas__pb2.ScalarResponse.SerializeToString,
            ),
            'Distinct': grpc.unary_unary_rpc_method_handler(
                    servicer.Distinct,
                    request_deserializer=dbaas__pb2.IROperation.FromString,
                    response_serializer=dbaas__pb2.DistinctResponse.SerializeToString,
            ),
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=dbaas__pb2.IROperation.FromString,
                    response_serializer=dbaas__pb2.JoinResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbaas.QueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dbaas.QueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryService(object):
    """─────────────────────────────────────────────
    MS6 — QUERY / AGGREGATION SERVICE
    ─────────────────────────────────────────────

    """

    @staticmethod
    def Count(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.QueryService/Count',
            dbaas__pb2.IROperation.SerializeToString,
            dbaas__pb2.ScalarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.QueryService/Sum',
            dbaas__pb2.IROperation.SerializeToString,
            dbaas__pb2.ScalarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Avg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.QueryService/Avg',
            dbaas__pb2.IROperation.SerializeToString,
            dbaas__pb2.ScalarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Distinct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.QueryService/Distinct',
            dbaas__pb2.IROperation.SerializeToString,
            dbaas__pb2.DistinctResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.QueryService/Join',
            dbaas__pb2.IROperation.SerializeToString,
            dbaas__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BrokerServiceStub(object):
    """─────────────────────────────────────────────
    MS2 — TRANSLATION BROKER
    El Gateway llama aquí. El broker parsea y enruta internamente.
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Process = channel.unary_unary(
                '/dbaas.BrokerService/Process',
                request_serializer=dbaas__pb2.BrokerRequest.SerializeToString,
                response_deserializer=dbaas__pb2.BrokerResponse.FromString,
                _registered_method=True)


class BrokerServiceServicer(object):
    """─────────────────────────────────────────────
    MS2 — TRANSLATION BROKER
    El Gateway llama aquí. El broker parsea y enruta internamente.
    ─────────────────────────────────────────────

    """

    def Process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Process': grpc.unary_unary_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=dbaas__pb2.BrokerRequest.FromString,
                    response_serializer=dbaas__pb2.BrokerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbaas.BrokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dbaas.BrokerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrokerService(object):
    """─────────────────────────────────────────────
    MS2 — TRANSLATION BROKER
    El Gateway llama aquí. El broker parsea y enruta internamente.
    ─────────────────────────────────────────────

    """

    @staticmethod
    def Process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.BrokerService/Process',
            dbaas__pb2.BrokerRequest.SerializeToString,
            dbaas__pb2.BrokerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GatewayServiceStub(object):
    """─────────────────────────────────────────────
    MS1 — API GATEWAY
    El cliente habla únicamente con este servicio.
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/dbaas.GatewayService/Login',
                request_serializer=dbaas__pb2.LoginRequest.SerializeToString,
                response_deserializer=dbaas__pb2.GatewayAuthResponse.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/dbaas.GatewayService/Register',
                request_serializer=dbaas__pb2.RegisterRequest.SerializeToString,
                response_deserializer=dbaas__pb2.GatewayAuthResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/dbaas.GatewayService/Execute',
                request_serializer=dbaas__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=dbaas__pb2.ExecuteResponse.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """─────────────────────────────────────────────
    MS1 — API GATEWAY
    El cliente habla únicamente con este servicio.
    ─────────────────────────────────────────────

    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=dbaas__pb2.LoginRequest.FromString,
                    response_serializer=dbaas__pb2.GatewayAuthResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=dbaas__pb2.RegisterRequest.FromString,
                    response_serializer=dbaas__pb2.GatewayAuthResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=dbaas__pb2.ExecuteRequest.FromString,
                    response_serializer=dbaas__pb2.ExecuteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbaas.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dbaas.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """─────────────────────────────────────────────
    MS1 — API GATEWAY
    El cliente habla únicamente con este servicio.
    ─────────────────────────────────────────────

    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.GatewayService/Login',
            dbaas__pb2.LoginRequest.SerializeToString,
            dbaas__pb2.GatewayAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.GatewayService/Register',
            dbaas__pb2.RegisterRequest.SerializeToString,
            dbaas__pb2.GatewayAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbaas.GatewayService/Execute',
            dbaas__pb2.ExecuteRequest.SerializeToString,
            dbaas__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
