# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculadora.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculadora.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\"C\n\x10\x45xpresionRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x01\x12\x0c\n\x04nums\x18\x02 \x03(\x01\x12\x13\n\x0boperaciones\x18\x03 \x03(\t\"5\n\x11\x45xpresionResponse\x12\x11\n\tresultado\x18\x01 \x01(\x01\x12\r\n\x05\x65rror\x18\x02 \x01(\t2O\n\x12\x43\x61lculadoraService\x12\x39\n\x10\x45valuarExpresion\x12\x11.ExpresionRequest\x1a\x12.ExpresionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXPRESIONREQUEST']._serialized_start=21
  _globals['_EXPRESIONREQUEST']._serialized_end=88
  _globals['_EXPRESIONRESPONSE']._serialized_start=90
  _globals['_EXPRESIONRESPONSE']._serialized_end=143
  _globals['_CALCULADORASERVICE']._serialized_start=145
  _globals['_CALCULADORASERVICE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
